services:
  - type: web
    name: ecom-ics-pairing-tool
    runtime: node
    plan: free

    buildFilter:
      paths:
        - web/**
        - server.js
        - package.json
        - package-lock.json
        - render.yaml

    buildCommand: npm install
    startCommand: npm start
